---
assessment:
# Predicition File (Only One  file allowed)
        file:                                                      /home/mcgerten/cafa3/CAFA_assessment_tool/ZZZ_1_9606.txt
# Information Content File (MUST be made before running)
        ic_path:                                             ./ICTool/ia.map
# OBO file used 
        obo_path:                                        ../CAFA3_test_data/gene_ontology_edit.obo.2016-06-01
# benchmark path
        benchmark_path:                       /home/mcgerten/cafa3/CAFA_assessment_tool/assessment/benchmark
# results path
        results_path:                                 ./results/
# Verbose option (Y, N)
        verbose :                         Y
# GAF file location                          
        gaf_path :                     goa_uniprot_all.gaf

plot:
# results path
        results:                            ./results/
# title is optional
        title:                                  9606
# Smoothing ( Y, N)
        smooth:                          N
# Files
# We recommend only plotting results for the same species together
# You can add up to 12 files
        file1:                                ZZZ_1_9606
        #file2:                             ZZZ_2_9606
        #file3:                             XXX_1_9606


