---
assessment:
# Predicition File (Only One  file allowed)
        prediction_path:                         /home/mcgerten/cafa3/CAFA_assessment_tool/ZZZ_1_9606.txt
# OBO file used 
        obo_path:                                        /home/mcgerten/cafa3/CAFA3_test_data/gene_ontology_edit.obo.2016-06-01
# benchmark path
        benchmark_path:                       /home/mcgerten/cafa3/CAFA3_test_data/benchmark20170605
# results path
        results_path:                                 /home/mcgerten/cafa3/CAFA3_test_data/results

# Information Content File (MUST be made before running)
        ic_path:                                             ./ICTool/ia.map
# GAF path                          
        gaf_path :                                         /home/mcgerten/cafa3/CAFA3_test_data/uniprot_exp_20170118_withoutTAS.txt

# Verbose option (Y, N)
        verbose :                                           Y

plot:
# results path
        results:                            ./results/
# title is optional
        title:                                  9606
# Smoothing ( Y, N)
        smooth:                          N
# Files
# We recommend only plotting results for the same species together
# You can add up to 12 files
        file1:                                ZZZ_1_9606
        #file2:                             ZZZ_2_9606
        #file3:                             XXX_1_9606


