---
assessment:
# Predicition File (Only One  file allowed)
        file:                                     ZZZ_1_9606.txt 
# Information Content File (MUST be made before running)
        ic_path:                           ./ICTool/ia.map
# OBO file used 
        obo_path:                      ./assessment/go_20170429.obo
# benchmark path
        benchmark_path:     ./assessment/benchmark/
# results path
        results_path:               ./results/
# Verbose option (Y, N)
        verbose :                         Y

plot:
# results path
        results:                            ./results/
# title is optional
        title:                                  9606
# Smoothing ( Y, N)
        smooth:                          N
# Files
# We recommend only plotting results for the same species together
# You can add up to 12 files
        file1:                                ZZZ_1_9606
        #file2:                             ZZZ_2_9606
        #file3:                             XXX_1_9606
