---
assess:
        file:                                    ZZZ_1_9606.txt 
	ic_file:                               ./ICTool/ia.map
        #Only One prediction file allowed
        obo:                                   ./check/go_20170429.obo
        benchmark:                  ./check/benchmark/
        results:                            ./results/
plot:
        results: ./results/
        title: 9606
        smooth: N
        file1: ZZZ_1_9606
        #file2: ZZZ_2_9606
        #file3: XXX_1_9606
        # Above files will be shown on one plot
        # We recommend only plotting results for the same species together
        # You can add up to 12 files
        # title is optional
